### ISSUE TITLE
serializer gem version

### ISSUE THREAD

**Issue by joelachance** [learn-co-curriculum/using-active-model-serializer-lab#4]
Hi, I wasn't able to complete this lab just using `gem 'active_model_serializers'`, it wouldn't create the JSON hash properly with this version, I needed to use `~> 0.8.0` for the hashes to work correctly. The returned hashes were missing the initial root (the 'products' key of the hash).

**Comment by kwebster2** [comment]
I experienced this issue on the Full Stack Web Developer track (v-0-0-0). The most recent version of the `active_model_serializers` gem (v '0.10.0') does not serialize deeply nested attributes by default, which are required to complete step 7 of the lab ("Update the OrderSerializer to include the product names of all products on that order, and display them with the order information after clicking More Info on /products.").  

Can be fixed in v10 by creating an initializer with`ActiveModel::Serializer.config.default_includes = '**'`, or an older version of the gem (v 0.9.5 worked for me) can be specified in the gemfile. 

@aturkewi @AnnJohn

**Comment by aturkewi** [comment]
@mendelB I think this is in your section, correct?

**Comment by cassaram09** [comment]
Was this updated on the master branch? Another student was having issues with this. I imagine this can be fixed by either including the appropriate ActiveModelSerializers version (and dependency versions) or updating the tests to reflect the most recent version of the AMS gem.

I fixed it for this student by changing the `gemfile.lock`. Replace:

`active_model_serializers (0.10.2)`
      `actionpack (>= 4.1, < 6)`
      `activemodel (>= 4.1, < 6)`
      `jsonapi (~> 0.1.1.beta2)`
      `railties (>= 4.1, < 6)`

with

`active_model_serializers (0.9.4)`
     `activemodel (>= 3.2)`

@aturkewi

**Comment by cassaram09** [comment]
Wondering if this was fixed yet? Another student was having a problem with this lab.  Same issue as my previous comment.

@aturkewi

**Comment by aturkewi** [comment]
Sorry @cassaram09 and thanks for pinging me twice! Merged this one in, so hopefully we're all set now :)

Thanks @mendelB !
